nsp_ds: "intake/raw_wiki_dataset"
mlm_ds: "intake/persentence_dataset"
args:
    buffer_size: 20000
    batch_size: 20
    mask_rate: 0.15
    window: 17
settings:
    epochs: 5
    epochs_per_test: 1
    epochs_per_save: 1
