path: "intake/raw_wiki_dataset"
args:
    buffer_size: 20000
    batch_size: 32
    mask_rate: 0.15
    context_rate: 0.15
    window: 17
settings:
    epochs: 1
    epochs_per_test: 1
    epochs_per_save: 1
