model: "intake/berte_pretrain"
tokenizer_args:
    add_bos: True
    add_eos: True
model_args:
    model_dim: 256
    latent_dim: 256
    num_heads: 8
    max_pe: 2000
    dff: 512
    dropout_rate: 0.4
    num_isolation_layers: 3
    num_perm_layers: 6
