tokenizer_args:
    add_bos: False
    add_eos: False
model_args:
    model_dim: 256
    memory_dim: 512
    num_heads: 8
    max_pe: 2000
    dff: 512
    dropout_rate: 0.4
    num_enc_layers: 3
    num_mem_enc_layers: 2
    num_mem_layers: 3
    num_perceiver_layers: 3
