model_args:
    unet_dim: 256
    model_dim: 256
    memory_dim: 512
    num_heads: 8
    dff: 512
    dropout_rate: 0.4
    num_mem_enc_layers: 2
    num_mem_layers: 3
    attention_dim: 256
    dim_mults: [1, 2, 4]
    convnext_mult: 2
